# Generated by Django 5.1.1 on 2024-09-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('apelido_usuario', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('email_usuario', models.EmailField(default='', max_length=254)),
            ],
        ),
    ]
